"""Adiciona media_recuperacao

Revision ID: 05aaf2239c6a
Revises: 730981a4c07e
Create Date: 2025-07-22 15:11:43.064417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05aaf2239c6a'
down_revision = '730981a4c07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
