"""Adiciona media_recuperacao na Escola

Revision ID: 730981a4c07e
Revises: fdf3d38d2928
Create Date: 2025-07-22 15:00:52.939942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730981a4c07e'
down_revision = 'fdf3d38d2928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escola', sa.Column('media_recuperacao', sa.Float(), server_default='6.0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escola', 'media_recuperacao')
    # ### end Alembic commands ###
