"""Adiciona tabela de documentos

Revision ID: 797616404d1d
Revises: 05aaf2239c6a
Create Date: 2025-07-23 14:11:23.745758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797616404d1d'
down_revision = '05aaf2239c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=300), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento')
    # ### end Alembic commands ###
