"""Criação inicial de todas as tabelas

Revision ID: aef63bf217b4
Revises: 
Create Date: 2025-07-10 11:13:33.144537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef63bf217b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('ano_letivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'escola_id', name='_ano_escola_uc')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'escola_id', name='_nome_escola_uc_disciplina')
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'escola_id', name='_nome_escola_uc_serie')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['ano_letivo.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tempo_limite', sa.Integer(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('regras_selecao', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['criador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_disciplinas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'disciplina_id')
    )
    op.create_table('professor_series',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'serie_id')
    )
    op.create_table('questao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('imagem_nome', sa.String(length=255), nullable=True),
    sa.Column('imagem_alt', sa.String(length=500), nullable=True, comment='Texto alternativo para acessibilidade'),
    sa.Column('nivel', sa.String(length=10), server_default='media', nullable=False, comment='Nível de dificuldade (facil, media, dificil)'),
    sa.Column('opcao_a', sa.Text(), nullable=True),
    sa.Column('opcao_b', sa.Text(), nullable=True),
    sa.Column('opcao_c', sa.Text(), nullable=True),
    sa.Column('opcao_d', sa.Text(), nullable=True),
    sa.Column('gabarito', sa.String(length=1), nullable=True),
    sa.Column('justificativa_gabarito', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serie_disciplinas',
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('serie_id', 'disciplina_id')
    )
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='prova', nullable=False),
    sa.Column('tempo_limite', sa.Integer(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=True),
    sa.Column('is_dinamica', sa.Boolean(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['ano_letivo.id'], ),
    sa.ForeignKeyConstraint(['criador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_avaliacao.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacao_alunos_designados',
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('avaliacao_id', 'usuario_id')
    )
    op.create_table('avaliacao_questoes',
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.PrimaryKeyConstraint('avaliacao_id', 'questao_id')
    )
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_realizacao', sa.DateTime(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('ano_letivo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['ano_letivo_id'], ['ano_letivo.id'], ),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulado_disciplinas',
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], ),
    sa.PrimaryKeyConstraint('avaliacao_id', 'disciplina_id')
    )
    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('resposta_aluno', sa.Text(), nullable=True),
    sa.Column('status_correcao', sa.String(length=20), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=True),
    sa.Column('feedback_professor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], ),
    sa.ForeignKeyConstraint(['resultado_id'], ['resultado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resposta')
    op.drop_table('simulado_disciplinas')
    op.drop_table('resultado')
    op.drop_table('avaliacao_questoes')
    op.drop_table('avaliacao_alunos_designados')
    op.drop_table('avaliacao')
    op.drop_table('serie_disciplinas')
    op.drop_table('questao')
    op.drop_table('professor_series')
    op.drop_table('professor_disciplinas')
    op.drop_table('modelo_avaliacao')
    op.drop_table('matricula')
    op.drop_table('usuario')
    op.drop_table('serie')
    op.drop_table('disciplina')
    op.drop_table('ano_letivo')
    op.drop_table('escola')
    # ### end Alembic commands ###
