"""Add ondelete SET NULL to Avaliacao.modelo_id

Revision ID: f8b837c39f97
Revises: f91860e19246
Create Date: 2025-07-28 15:35:08.241973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b837c39f97'
down_revision = 'f91860e19246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('avaliacao_modelo_id_fkey'), 'avaliacao', type_='foreignkey')
    op.create_foreign_key(None, 'avaliacao', 'modelo_avaliacao', ['modelo_id'], ['id'], ondelete='SET NULL')
    op.add_column('usuario', sa.Column('data_aceite_termos', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'data_aceite_termos')
    op.drop_constraint(None, 'avaliacao', type_='foreignkey')
    op.create_foreign_key(op.f('avaliacao_modelo_id_fkey'), 'avaliacao', 'modelo_avaliacao', ['modelo_id'], ['id'])
    # ### end Alembic commands ###
