"""alteracao do public_base e base

Revision ID: f91860e19246
Revises: 797616404d1d
Create Date: 2025-07-23 14:43:02.586895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91860e19246'
down_revision = '797616404d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
