"""Adiciona coluna de plano a tabela Escola

Revision ID: fdf3d38d2928
Revises: 871078c8ed46
Create Date: 2025-07-16 15:19:23.232198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf3d38d2928'
down_revision = '871078c8ed46'
branch_labels = None
depends_on = None


def upgrade():
     # ### Comandos ajustados para lidar com dados existentes ###
    
    # Passo 1: Adiciona a coluna, mas permite que ela seja nula temporariamente.
    op.add_column('escola', sa.Column('plano', sa.String(length=20), nullable=True))
    
    # Passo 2: Atualiza todas as escolas existentes para terem o plano 'essencial' como padrão.
    op.execute("UPDATE escola SET plano = 'essencial' WHERE plano IS NULL")
    
    # Passo 3: Agora que não há mais valores nulos, altera a coluna para ser obrigatória (NOT NULL).
    op.alter_column('escola', 'plano', nullable=False)
    
    # ### Fim dos comandos ajustados ###
   

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escola', 'plano')
    # ### end Alembic commands ###
